spring:
  application:
    name: var

  jpa:
    hibernate:
      ddl-auto: create # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true
      open-in-view: true
      use_sql_comments: true
      show_sql: true

  profiles:
#    include: database, redis, mail, jwt, storage, port
    include: database, mail, jwt, port, oauth, redis

logging:
  level:
    org.hibernate.sql: debug